@startuml scenario1
autonumber

title "Scenario 1: barrower pay debt before period ends"

actor Borrower
participant DAIContract
participant CollateralizedLeverage as CLContract
actor Lender

Borrower -> CLContract: newLoanRequest(collateralAmount in ETH)
Borrower -> Lender: address (via whatsapp, discord, email phone etc :D )
Lender -> CLContract: viewLoanRecord(address)
CLContract --> Lender: requestedAmountInDAI (half worth of collateralAmount in DAI)
Lender -> DAIContract: approve(CLContract address, requestedAmountInDAI)
Lender -> CLContract: acceptLoanRequest(address)
CLContract -> DAIContract: transferFrom(lender, borrower, requestedAmountInDAI)
DAIContract -> Borrower: transfer(requestedAmountInDAI)
...
Borrower -> CLContract: currendDebt()
CLContract --> Borrower: currentDebthAmountInDAI
Borrower -> DAIContract: approve(CLContract address, currentDebthAmountInDAI)
Borrower -> CLContract: payDebt(currentDebthAmountInDAI)
CLContract -> DAIContract: transferFrom(borrower, lender, currentDebthAmountInDAI)
DAIContract -> Lender: transfer(currentDebthAmountInDAI)

@enduml